feat: eureka注册发现支持命名空间隔离
polarismesh/polaris pull request #1068
Opened 2023-04-07 03:59 UTC by self-made-boy

**Please provide issue(s) of this PR:**
Fixes #

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ x ] ApiServer
- [ ] Auth
- [ ] Configuration
- [ ] Naming
- [ ] HealthCheck
- [ ] Metrics
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2023-04-07 11:49 UTC, andrewshan commented on apiserver/eurekaserver/access.go
> +	HeaderNamespace string = "X-Polaris-Namespace"
x-namespace

2023-04-07 12:38 UTC, andrewshan commented on apiserver/eurekaserver/delta_worker.go
> +	if work, exist := a.workers.Load(namespace); exist {
这里最好加个锁

2023-04-07 12:38 UTC, andrewshan commented on apiserver/eurekaserver/delta_worker.go
> +	workers                *sync.Map
不用syncmap，用普通map+读写锁吧

2023-04-07 12:56 UTC, andrewshan commented on apiserver/eurekaserver/model.go
> +	Namespace          string        `json:"namespace"`
这个是没有的，eureka同步的时候，不会带这个过来

2023-04-07 13:05 UTC, andrewshan requested changes
1. 修改header的key
2. 使用读写锁+map
3. replicate的namespace不应该从body里面取
4. 这边发送replicate请求时，也应该把namespace带上

2023-04-11 02:15 UTC, andrewshan commented on apiserver/eurekaserver/delta_worker.go
> +		work := NewApplicationsWorker(a.interval, a.deltaExpireInterval, a.enableSelfPreservation,
这里要再检查一下是否存在，在锁里面再进行一次判断
work, exist := a.workers[namespace]
if exist {
		return work
}

2023-04-11 02:16 UTC, andrewshan commented on apiserver/eurekaserver/delta_worker.go
> +	} else {
这里没有必要写else

2023-04-11 02:19 UTC, andrewshan commented on apiserver/eurekaserver/server.go
> +func parsePeersToReplicate(defaultNamespace string, replicatePeerObjs []interface{}) map[string][]string {
这个方法要用测试用例来验证下

2023-04-11 03:33 UTC, andrewshan commented on apiserver/eurekaserver/access.go
> +	appsRespCache := h.workers.Get(namespace).GetDeltaApps()
h.workers.Get(namespace)，提取成一个变量

2023-04-11 07:47 UTC, chuntaojun approved these changes

2023-04-13 07:12 UTC, merged