Feature/decoupling auth model issue 1084
polarismesh/polaris pull request #1126
Opened 2023-05-14 15:21 UTC by KarKLi

**Please provide issue(s) of this PR:**
Fixes #

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] ApiServer
- [X] Auth
- [ ] Configuration
- [ ] Naming
- [ ] HealthCheck
- [ ] Metrics
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

Remove AuthServer and split it into UserOperator and StrategyOperator.

Change notes:

- Remove AuthServer
- Migrate GetAuthChecker&AfterResourceOperation method into StrategyOperator
- Migrate Login method into UserOperator
- Migrate GroupOperator into UserOperator, so it can be a part of UserOperator (group is a set of user)

- [X] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2023-05-15 01:42 UTC, chuntaojun commented on auth/api.go
>  type UserOperator interface {
UserOperator => UserServer

2023-05-15 01:42 UTC, chuntaojun commented on auth/api.go
>  type StrategyOperator interface {
StrategyServer

2023-05-15 01:42 UTC, chuntaojun commented on auth/auth.go
> +	StrategyMgnSlots[name] = s
StrategyMgnSlots = strategyMgnSlots

2023-05-15 01:42 UTC, chuntaojun commented on auth/defaultauth/strategy_authability.go
> +func (svr *startegyAuthAbility) Initialize(authOpt *auth.Config, storage store.Store,
startegyAuthAbility => strategyAuthAbility

2023-05-15 01:42 UTC, chuntaojun commented on auth/defaultauth/strategy_test.go
> +				"salt":        "polarismesh@2021",
salt 配置应该是 User 的配置，Strategy 对于 Token 的解析交给 UserServer 进行处理

2023-05-15 14:07 UTC, chuntaojun requested changes

2023-05-16 14:59 UTC, KarKLi commented on auth/auth.go
> +	name := authOpt.User.Name
在defaultauth中的auth_checker_test.go添加了单测。

2023-05-16 14:59 UTC, KarKLi commented on release/standalone/docker-compose/server/polaris-server.yaml
> +      salt: polarismesh@2021
已统一修改，下同

2023-05-16 16:08 UTC, chuntaojun commented
需要修复下CI

2023-05-18 15:11 UTC, KarKLi commented on auth/defaultauth/auth_checker.go
> +	var strategyContentBytes []byte
done

2023-05-19 16:52 UTC, merged