Develop
polarismesh/polaris pull request #1271
Opened 2023-10-20 08:19 UTC by skywli

**Please provide issue(s) of this PR:**
Fixes #

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] ApiServer
- [ ] Auth
- [ X] Configuration
- [ ] Naming
- [ ] HealthCheck
- [ ] Metrics
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2023-10-24 02:23 UTC, chuntaojun requested changes

2023-11-07 06:05 UTC, skywli commented on apiserver/httpserver/config/console_access.go
> -	requestId := ctx.Value(utils.StringContext("request-id"))
这里handler.Parse(configFile) 可能会返回err, ctx 是nil

2023-11-07 06:13 UTC, skywli commented on common/model/config_file.go
> +	return fmt.Sprintf("%v@%v@%v@%v", c.Namespace, c.Group, c.FileName, c.Typ)
这里有c.Typ 非string,  sprintf 明了清晰， 服务性能都不在这里

2023-11-07 06:59 UTC, skywli commented on common/model/config_file.go
> +	Typ       ConfigeFileType
modify

2023-11-10 08:32 UTC, chuntaojun requested changes

2023-11-10 08:32 UTC, chuntaojun commented on cache/config/config_file.go
> +	// 如果有旧版本cache， 先删除再保存
不要这么处理，很容易出现前一刻可以获取到配置，后一刻获取不到

2023-11-13 02:19 UTC, skywli commented on cache/config/config_file.go
> +	// 如果有旧版本cache， 先删除再保存
从灰度到全量， 这里要删除灰度版本，否则灰度一直存在。 在版本更新的过程中，如果没有客户端正在拉配置，这里没有什么影响。 如果有客户端正在拉配置，可能拉不到，但是等到配置更新完成，就能通过通知拉到最新配置。

2023-11-13 02:45 UTC, chuntaojun commented on cache/config/config_file.go
> +	// 如果有旧版本cache， 先删除再保存
灰度到全量，应该是先删除灰度的发布，然后在重新 Publish 一次全量的才对

2023-11-15 15:58 UTC, merged