WIP:Use sharedmap to optimize performance
polarismesh/polaris pull request #206
Opened 2021-12-25 05:53 UTC by liu-song

**Please provide issue(s) of this PR:**
Fixes #https://github.com/polarismesh/polaris/issues/205

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Naming
- [X] HealthCheck
- [] Test and Release

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.
benchmark 
```
goos: windows
goarch: amd64
pkg: github.com/polarismesh/polaris-server/common/sharedmap
cpu: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
BenchmarkSyncMap
BenchmarkSyncMap-8               1163235               893.6 ns/op           141 B/op          4 allocs/op
BenchmarkMutexMap
BenchmarkMutexMap-8              3011132               480.6 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap2
BenchmarkSharedMap2-8            3291242               353.1 ns/op             9 B/op          2 allocs/op
BenchmarkSharedMap4
BenchmarkSharedMap4-8            3818988               307.1 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap8
BenchmarkSharedMap8-8            5638132               214.2 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap16
BenchmarkSharedMap16-8           7525195               164.6 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap32
BenchmarkSharedMap32-8           8193496               147.8 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap64
BenchmarkSharedMap64-8           8463386               146.4 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap128
BenchmarkSharedMap128-8          8684839               139.7 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap256
BenchmarkSharedMap256-8          9255338               139.5 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap512
BenchmarkSharedMap512-8          9228958               135.2 ns/op            24 B/op          3 allocs/op
BenchmarkSharedMap1024
BenchmarkSharedMap1024-8         9414518               133.3 ns/op            24 B/op          3 allocs/op

```

因为实际场景下并发读写，所以将get, set,del 三个操作放一起执行了。使用分片还是能取得一定程度的上的优化，对于size 到了一定程度再调大似乎没有太大的作用，我本机的核心数是8，感觉这个后面可以换成运行环境的核心数乘以16 或者32 之类。目前这个测试中相当于是读写的比例是1:2（get:set+del),如果有必要的话感觉可以将这个线上实际读写的比例，来调下这个size.

2021-12-25 09:19 UTC, chuntaojun requested changes

2021-12-25 09:19 UTC, chuntaojun commented on common/sharedmap/sharedmap.go
> +	healthCheckInstances map[string]*healthcheck.InstanceWithChecker
*healthcheck.InstanceWithChecker => interface{}

2021-12-25 11:14 UTC, liu-song commented on common/sharedmap/sharedmap.go
> +	healthCheckInstances map[string]*healthcheck.InstanceWithChecker
这里我也想了一下，是把sharedmap换成interface{}个作为一个普遍使用的map，还是仅仅只给healthcheck.InstanceWithChecker 使用，因为换成interface{}的话会存在 interface{}-》*healthcheck.InstanceWithChecker之间转换的消耗。如果其他场景不使用的话，感觉还是直接*healthcheck.InstanceWithChecker好些？

2021-12-26 05:37 UTC, chuntaojun commented on common/sharedmap/sharedmap.go
> +	healthCheckInstances map[string]*healthcheck.InstanceWithChecker
那就不能放在common包下面，你应该直接放在 healthchecker 里面才对，common应该是放一些公共的，如果这个sharedmap 不能公用的话，还是回到 heathcheck 里面

2021-12-26 06:42 UTC, liu-song commented on common/sharedmap/sharedmap.go
> +	healthCheckInstances map[string]*healthcheck.InstanceWithChecker
OK，我后面改一下

2021-12-27 02:48 UTC, chuntaojun commented on common/sharedmap/sharedmap.go
> +func (m *SharedMap) store(instanceId string, healthCheckInstance *healthcheck.InstanceWithChecker) {
I think if healthCheckInstance == nil, need to return false or error

2022-01-03 08:10 UTC, liu-song commented on common/sharedmap/sharedmap.go
> +func (m *SharedMap) store(instanceId string, healthCheckInstance *healthcheck.InstanceWithChecker) {
看了一下store 相关的上下文，healthCheckInstance  应该不会nil, 目前每次store 的时候healthCheckInstance 都是newInstanceWithChecker()得到的,先不加了吧，加了就多一次判断了

2022-01-05 11:49 UTC, chuntaojun commented on healthcheck/cache.go
> +	value, ok := values.Load(instanceId)
这里会有并发Store同一个key的问题，本意是只希望Store一次，但是目前的改法的话，做不到只Store一次，最好可有有一个类似PutIfAbsent的语意

2022-01-05 11:49 UTC, chuntaojun commented on healthcheck/shardmap.go
> +		shard.healthCheckMutex.Lock()
这里为什么要用写锁呢？

2022-01-05 11:49 UTC, chuntaojun commented on healthcheck/shardmap.go
> +func (m *ShardMap) Count() int {
这里应该标注下，这个Count不是一个准确值，只能是一个近似值

2022-01-05 12:06 UTC, liu-song commented on healthcheck/shardmap.go
> +func (m *ShardMap) Count() int {
用了分片的话，这里的确是个近似值，我改下

2022-01-13 04:20 UTC, chuntaojun commented
pls resolve code conflict

2022-01-13 04:27 UTC, liu-song commented
> pls resolve code conflict

ok ，我后面一起解决

2022-01-17 03:24 UTC, liu-song commented
我这周重新提交一个新的pr，这个先关 了

2022-01-17 03:24 UTC, closed without merging