支持配置中心能力
polarismesh/polaris pull request #226
Opened 2022-01-07 06:21 UTC by lepdou

**Please provide issue(s) of this PR:**
Fixes #225 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-01-07 09:52 UTC, chuntaojun commented on config/service/api.go
> +	StartTxAndSetToContext(ctx context.Context) (*sql.Tx, context.Context, error)
这里不能再业务逻辑层耦合具体的存储层的相关实现，不然是没办法做到store插件化的

2022-01-07 09:52 UTC, chuntaojun commented on config/service/common.go
> +	tx, err := cs.storage.StartTx()
同理，这里在业务逻辑层耦合了具体存储的相关api，这里是不太合适北极星本身的设计

2022-01-08 04:56 UTC, chuntaojun commented on apiserver/httpserver/config_client_access.go
> +	m := jsonpb.Marshaler{Indent: " ", EmitDefaults: true}
这里应该是返回api.XXXResponse结构体吧？

2022-01-08 04:56 UTC, chuntaojun commented on apiserver/httpserver/config_client_access.go
> +	watchConfigFileRequest := &api.ClientWatchConfigFileRequest{}
这里的逻辑应该在ConfigAPI做吧？grpc 和http两个协议层都有可能需要，

2022-01-08 04:56 UTC, chuntaojun commented on apiserver/httpserver/config_client_access.go
> +	group := req.QueryParameter("group")
我觉得协议层应该只负责把请求体转为对应的数据之后，直接传递给ConfigServer操作，不负责具体的参数检查

2022-01-08 05:06 UTC, chuntaojun commented on apiserver/httpserver/config_console_access.go
> +	context, err := handler.Parse(configFile)
context=> ctx

2022-01-08 05:09 UTC, chuntaojun commented on apiserver/httpserver/watcher.go
> +	configFileWatchers *sync.Map
这里的设计感觉不太好，这里应该只需要管理被hold住的链接，监听逻辑在configservice做完，由apiserver传递给service一个通用回掉者，在configservice去操作这些

2022-01-08 05:12 UTC, chuntaojun commented on cache/config_file.go
> +type FileCache struct {
如果自动失效的话，存储层出现问题server这里怎么容灾呢

2022-01-08 05:13 UTC, chuntaojun commented on cache/config_file.go
> +	lockObj, _ := fc.fileLoadLocks.LoadOrStore(fileId, new(sync.Mutex))
可以用single light

2022-01-09 14:25 UTC, liu-song commented on config/service/config_file_tag.go
> +		newTagValues := newTagMap[key]
这里的newTagValues 就是上面newTagMap的value 吧，可以简化一下~

2022-01-09 14:25 UTC, liu-song commented on config/service/config_file_tag.go
> +		newTagValues := newTagMap[key]
同上~

2022-01-10 11:45 UTC, lepdou commented on apiserver/httpserver/config_client_access.go
> +	watchConfigFileRequest := &api.ClientWatchConfigFileRequest{}
这里就是从协议里反序列化出请求数据，一行代码。应该是在 api层做？

2022-01-10 11:46 UTC, lepdou commented on apiserver/httpserver/config_client_access.go
> +	m := jsonpb.Marshaler{Indent: " ", EmitDefaults: true}
已修复

2022-01-10 11:52 UTC, lepdou commented on apiserver/httpserver/config_client_access.go
> +	group := req.QueryParameter("group")
我理解协议层做为 API 层与其它系统的交互门面，参数校验的逻辑是属于 API 层的范畴。参数有问题，越早返回越好。而不是透传到核心业务层才校验

2022-01-10 11:53 UTC, lepdou commented on apiserver/httpserver/config_console_access.go
> +	context, err := handler.Parse(configFile)
done

2022-01-10 12:37 UTC, chuntaojun commented on apiserver/httpserver/config_client_access.go
> +	watchConfigFileRequest := &api.ClientWatchConfigFileRequest{}
是指这接下来的逻辑，除了请求序列化

2022-01-10 14:49 UTC, lepdou commented on config/event.go
> +type Event struct {
done

2022-01-10 14:50 UTC, lepdou commented on config/server.go
> +func (cs *Server) WatchPublishConfigEvent(handler func(event Event) bool) {
这个方法重构掉了，已经没有了

2022-01-10 14:51 UTC, lepdou commented on config/service/api.go
> +	StartTxAndSetToContext(ctx context.Context) (*sql.Tx, context.Context, error)
done

2022-01-10 14:51 UTC, lepdou commented on config/service/common.go
> +	tx, err := cs.storage.StartTx()
done

2022-01-10 14:53 UTC, lepdou commented on apiserver/httpserver/watcher.go
> +	configFileWatchers *sync.Map
可以，已更新

2022-01-10 15:10 UTC, lepdou commented on cache/config_file.go
> +type FileCache struct {
优化成到失效时间后，更新缓存，而不是删除缓存。

2022-01-11 09:32 UTC, chuntaojun commented on config/service/config_file_release.go
> +func (cs *Impl) PublishConfigFile(ctx context.Context, configFileRelease *api.ConfigFileRelease) *api.ConfigResponse {
这块逻辑的代码行数，是不是有点多了

2022-01-12 10:32 UTC, chuntaojun commented on apiserver/httpserver/config_client_access.go
> +	finishChan := make(chan interface{})
make(chan interface{}) => make(chan struct{})

2022-01-12 10:32 UTC, chuntaojun commented on apiserver/httpserver/config_connection_manager.go
> +	finishChan chan interface{}
replace to chan struct{}

2022-01-12 10:32 UTC, chuntaojun commented on config/scanner.go
> +				s.eventCenter.handlerEvent(Event{
这里是不是可以攒成一批来处理？收集需要通知的event，一把 handleEvent

2022-01-12 10:32 UTC, chuntaojun commented on config/scanner.go
> +				s.eventCenter.handlerEvent(Event{
handlerEvent => handleEvent

2022-01-13 03:22 UTC, chuntaojun approved these changes

2022-01-14 03:10 UTC, andrewshan commented on apiserver/httpserver/config_client_access.go
> +func (h *HTTPServer) WatchConfigFile(req *restful.Request, rsp *restful.Response) {
所有对外暴露的方法都需要按照go代码规范来提交注释

2022-01-14 03:10 UTC, andrewshan commented on apiserver/httpserver/config_client_access.go
> +	DefaultLongPollingTimeout = 30000 * time.Millisecond
如果没有跨package调用，变量首字母用小写

2022-01-14 03:11 UTC, andrewshan commented on apiserver/httpserver/config_client_access.go
> +	log.GetConfigLogger().Info("[Config][Client] client get config file success.",
这个改成GetConfigScope吧

2022-01-14 03:16 UTC, andrewshan commented on apiserver/httpserver/config_connection_manager.go
> +	conns.Store(clientId, &connection{
clientId是怎么生成的？会不会出现相同的clientId，使用不同的connection的情况？

2022-01-14 03:18 UTC, chuntaojun commented on apiserver/httpserver/config_connection_manager.go
> +	conns.Store(clientId, &connection{
id, _ := uuid.NewUUID()
clientId := clientAddr + "@" + id.String()[0:8]

2022-01-14 03:18 UTC, chuntaojun commented on apiserver/httpserver/config_connection_manager.go
> +	conns.Store(clientId, &connection{
看实现的话，应该是不会的

2022-01-14 03:20 UTC, andrewshan commented on apiserver/httpserver/config_client_access.go
> +	timer := time.NewTimer(DefaultLongPollingTimeout)
每一个连接上来一个timer的话，golang的timer实现和其他语言不太一样，非常耗CPU，建议使用全局一个timer

2022-01-14 03:26 UTC, chuntaojun commented on apiserver/httpserver/config_client_access.go
> +	timer := time.NewTimer(DefaultLongPollingTimeout)
这里是不是换成时间轮会好一点？这里是每一个客户端监听时自己的超时时间

2022-01-14 03:30 UTC, andrewshan commented on apiserver/httpserver/config_client_access.go
> +/*
除了代码外，还需要把接口文档补齐

2022-01-14 03:42 UTC, andrewshan commented on apiserver/httpserver/config_console_access.go
> +	namespace := handler.QueryParameter("namespace")
这里建议对参数进行校验，包括前面的HTTP接口也是一样

2022-01-14 03:45 UTC, andrewshan commented on apiserver/httpserver/config_server.go
> +func (h *HTTPServer) GetConfigAccessServer(include []string) (*restful.WebService, error) {
需要确认这里的接口是否有统计返回码数据

2022-01-14 03:48 UTC, andrewshan commented on store/boltdb/config_file_tag.go
> +func (t *configFileTagStore) CreateConfigFileTag(tx store.Tx, fileTag *model.ConfigFileTag) error {
boltdb需要实现，否则用户没法在单机版运行

2022-01-14 04:01 UTC, andrewshan commented on cache/config_file.go
> +	go func() {
1.这个协程没有退出条件，建议通过context来传递退出信号
2. ticker也没有关闭

2022-01-14 04:02 UTC, andrewshan commented on cache/config_file.go
> +	t := time.NewTicker(time.Minute)
同样问题：
1. 没有传入退出信号
2. ticker没有关闭

2022-01-14 04:04 UTC, andrewshan commented on config/watcher.go
> +	go func() {
按照上次讨论，这个协程是否有存在必要？

2022-01-14 04:05 UTC, andrewshan commented on config/watcher.go
> +				log.GetDefaultLogger().Error("[Config][Watcher] handler config release message error.", zap.Any("error", err))
这个应该打到ConfigLogger里面？

2022-01-14 04:10 UTC, andrewshan commented on cache/config_file.go
> +	BaseExpireTimeAfterWrite = 60 * 60 // expire after 1 hour
这些参数是否考虑开放配置？

2022-01-14 04:12 UTC, andrewshan requested changes
关键几个问题：
1. 部分export接口缺少注释
2. 接口参数需要进行校验
3. 单协程推送是否存在性能瓶颈？

2022-01-18 07:07 UTC, andrewshan approved these changes
LGTM

2022-01-18 08:20 UTC, merged