Add polaris namespace for deploying in k8s
polarismesh/polaris pull request #339
Opened 2022-04-17 15:53 UTC by MIBc

- [X ] Installation

Add polaris namespace for deploying in k8s.

2022-04-17 16:46 UTC, chuntaojun requested changes

2022-04-17 16:46 UTC, chuntaojun commented on deploy/helm/templates/polaris-console-config.yaml
> +  namespace: polaris
helm 的话，建议这个不写死polaris了，改为 {{ .Release.Namespace }} 吧

2022-04-19 04:33 UTC, MIBc commented on deploy/helm/templates/polaris-console-config.yaml
> +  namespace: polaris
done

2022-04-19 04:45 UTC, chuntaojun approved these changes

2022-04-22 05:39 UTC, merged