bugfix: fix(#448) redis pool with config error
polarismesh/polaris pull request #449
Opened 2022-06-17 04:09 UTC by edocevol

**Please provide issue(s) of this PR:**
Fixes #448 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [x] Configuration
- [ ] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-06-17 05:09 UTC, chuntaojun requested changes

2022-06-17 05:09 UTC, chuntaojun commented on common/redispool/config_option.go
> +		_ = copier.CopyWithOption(c, newConfig, copier.Option{IgnoreEmpty: true, DeepCopy: true})
just *c = *newConfig is ok

2022-06-17 06:26 UTC, edocevol commented on common/redispool/config_option.go
> +		_ = copier.CopyWithOption(c, newConfig, copier.Option{IgnoreEmpty: true, DeepCopy: true})
Great!

2022-06-17 09:05 UTC, chuntaojun approved these changes

2022-06-17 09:51 UTC, chuntaojun approved these changes

2022-06-18 00:14 UTC, daheige commented
Here is to overwrite the value, it will be processed automatically, no * is needed, please see the unit test case and the newpool usage of Polaris.
This is not a bug.

2022-06-20 14:13 UTC, edocevol commented
https://github.com/polarismesh/polaris/pull/454

2022-06-20 14:13 UTC, closed without merging