fix:discoverevent 添加上报日志到loki插件 (#648)
polarismesh/polaris pull request #708
Opened 2022-09-29 08:57 UTC by alexwanglei

* fix issue #648

* fix:discoverevent添加插件上报日志到loki

2022-09-29 09:13 UTC, chuntaojun requested changes

2022-09-29 09:13 UTC, chuntaojun commented on polaris-server.yaml
> +    name: discoverEventLoki
name: discoverEventLocal
    # option:
    #   queueSize: 1024
    #   outputPath: ./discover-event
    #   rotationMaxSize: 500
    #   rotationMaxAge: 8
    #   rotationMaxBackups: 100

    # name: discoverEventLoki
    # option:
      # queueSize: 1024
      # pushURL: http://127.0.0.1:3100/loki/api/v1/push
      # tenantID: "test"
      # labels:
      #   env: "test"
      #   app: "polaris"

2022-09-29 09:13 UTC, chuntaojun commented on polaris-server.yaml
> +    name: discoverEventLoki
默认使用 local 插件， loki 的这里默认注释，不然默认会导致这个插件有问题

2022-09-29 09:24 UTC, alexwanglei commented on polaris-server.yaml
> +    name: discoverEventLoki
已修改

2022-09-29 10:17 UTC, shichaoyuan commented on plugin/discoverevent/loki/event_loki.go
> +	syncLock       *sync.Mutex
uber 的编码规范建议 Mutext 不要用指针类型

2022-09-29 10:17 UTC, shichaoyuan commented on plugin/discoverevent/loki/event_loki.go
> +		event := eventHolder.Next()
这个goroutine在读，另外Run那个goroutine在写，会不会有问题？

2022-09-29 10:20 UTC, chuntaojun requested changes

2022-09-29 10:20 UTC, chuntaojun commented on plugin/discoverevent/loki/event_loki.go
> +				go d.pushLoki(d.curEventBuffer)
需要触发下切换eventBuffer，不然会有问题

2022-09-29 10:20 UTC, chuntaojun commented on plugin/discoverevent/loki/event_loki.go
> +		event := eventHolder.Next()
确实，需要在Run里面，每一次go pushLoki 的时候做一下 switchBuffer

2022-09-29 11:24 UTC, andrewshan commented on plugin/discoverevent/loki/event_loki.go
> +	d.syncLock = sync.Mutex{}
非指针类型不需要初始化

2022-09-29 11:27 UTC, andrewshan commented on common/model/naming.go
> +	CreateTime    time.Time
CreateTime和CreateTimeSec保留一个就行了

2022-09-29 11:29 UTC, andrewshan commented on plugin/discoverevent/loki/event_loki.go
> +	bufferPool     *sync.Pool
这里用sync.Pool的目的是啥？

2022-09-29 11:39 UTC, andrewshan commented on plugin/discoverevent/loki/event_loki.go
> +	d.syncLock.Lock()
这个实现有点太复杂，如果要实现批处理的话，可以使用channel来按照，当队列成员满足N个成员，或者达到一定的时间后，就进行处理，可以参考北极星的批处理逻辑：https://github.com/polarismesh/polaris/blob/main/service/batch/client.go

2022-09-29 11:45 UTC, andrewshan commented on plugin/discoverevent/loki/event_loki.go
> +	syncInterval := time.NewTicker(time.Duration(10) * time.Second)
syncInterval，这个ticker没有关闭

2022-09-29 12:47 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +	syncInterval := time.NewTicker(time.Duration(10) * time.Second)
已修改

2022-09-29 12:47 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +				go d.pushLoki(d.curEventBuffer)
已修改

2022-09-29 12:47 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +		event := eventHolder.Next()
已修改

2022-09-29 12:47 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +	bufferPool     *sync.Pool
这里是用来复用eventbuffer对象的

2022-09-29 12:48 UTC, alexwanglei commented on common/model/naming.go
> +	CreateTime    time.Time
已修改

2022-09-30 07:55 UTC, chuntaojun approved these changes

2022-09-30 08:39 UTC, shichaoyuan commented on plugin/discoverevent/loki/event_loki.go
> +		d.syncLock.Unlock()
这个锁有什么用？

2022-09-30 08:39 UTC, shichaoyuan commented on plugin/discoverevent/loki/event_loki.go
> +			go d.pushLoki(d.curEventBuffer)
日志发送会不会乱序？  可以接受？

2022-09-30 08:43 UTC, chuntaojun commented on plugin/discoverevent/loki/event_loki.go
> +			go d.pushLoki(d.curEventBuffer)
日志乱序应该还好，事件的时间不乱序就行，这个后面可以在优化下

2022-09-30 10:46 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +		d.syncLock.Unlock()
感觉是为了防止多个goroutine从eventBuffer中读取日志发送，导致日志重复。但是因为异步执行pushLoki后， 就调用了switchEventBuffer，等于重新创建了一个新的eventBuffer，之前的eventBuffer不会被其他goroutine共享，所以应该没必要加锁。 @chuntaojun

2022-09-30 13:05 UTC, chuntaojun commented on plugin/discoverevent/loki/event_loki.go
> +		d.syncLock.Unlock()
确实，不过乱序还是想避免下，我感觉其实都没必要什么 sync.Pool，就 chan 接收直接消费就好了，把 chan 开大点就是

2022-10-04 03:51 UTC, alexwanglei commented
> @alexwanglei pls fix ci

好了，再触发试一下

2022-10-04 03:57 UTC, chuntaojun requested changes

2022-10-04 03:57 UTC, chuntaojun commented on plugin/discoverevent/loki/event_loki.go
> +				go d.eventLog.Log(batch[:batchSize])
这个 go 的移步去掉吧

2022-10-04 03:57 UTC, chuntaojun commented on plugin/discoverevent/loki/event_loki.go
> +				go d.eventLog.Log(batch[:batchSize])
同上

2022-10-04 03:57 UTC, chuntaojun commented on plugin/discoverevent/loki/event_loki.go
> +				go d.eventLog.Log(batch[:batchSize])
同上

2022-10-05 04:07 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +				go d.eventLog.Log(batch[:batchSize])
done

2022-10-05 04:07 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +				go d.eventLog.Log(batch[:batchSize])
done

2022-10-05 04:07 UTC, alexwanglei commented on plugin/discoverevent/loki/event_loki.go
> +				go d.eventLog.Log(batch[:batchSize])
done

2022-10-05 23:39 UTC, merged