fix(bootstrap): return error from Start function
polarismesh/polaris pull request #727
Opened 2022-10-10 12:01 UTC by Davincible

**About this PR**
I would like to start a Polaris server directly from Go, to use when I run my tests. I found that I can use the `bootstrap.Start` function for this. However, this function was printing out errors, instead of returning them. I would like to print the errors from my custom logger (and it is not idiomatic in Go to not return errors directly), I changed the startup function to return an error, and let the CLI print it out instead.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [x] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-10-11 00:46 UTC, chuntaojun requested changes

2022-10-11 00:46 UTC, chuntaojun commented on bootstrap/server.go
> +	return string(config), nil
It will block here, unless there is an exception or the program actively exits, it will go to this return

2022-10-11 00:46 UTC, chuntaojun commented on bootstrap/server.go
> -	fmt.Println("finish starting server")
pls keep this print

2022-10-11 01:26 UTC, daheige commented on bootstrap/server.go
> -	fmt.Println("finish starting server")
> pls keep this print

yes

2023-02-23 02:48 UTC, daheige commented
Please resolve the conflict, thank you

2023-05-14 04:08 UTC, closed without merging