Main issue#672
polarismesh/polaris pull request #735
Opened 2022-10-11 07:15 UTC by hoErYu

**Please provide issue(s) of this PR:**
Fixes #672 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-10-12 09:41 UTC, chuntaojun commented
pls fix code conflict

2022-10-12 10:46 UTC, hoErYu commented
> pls fix code conflict

done

2022-10-12 14:07 UTC, chuntaojun commented
ci 有点问题，建议本地跑一下 CI 中的相关测试命令看下结果

2022-10-12 14:27 UTC, houseme approved these changes

2022-10-12 16:16 UTC, hoErYu commented
> ci 有点问题，建议本地跑一下 CI 中的相关测试命令看下结果

修复了相关测试

2022-10-12 23:56 UTC, houseme commented on plugin/auth/platform/platform.go
> +	commonLog "github.com/polarismesh/polaris/common/log"
import

2022-10-12 23:57 UTC, houseme commented on plugin/discoverevent/local/event_local.go
> +	commonLog "github.com/polarismesh/polaris/common/log"
import

2022-10-13 00:15 UTC, houseme reviewed
import 按组处理，官方包一组，第三方包一组，项目包一组

2022-10-13 00:20 UTC, daheige commented
Yes, it can be set in the editor goland.


------------------ 原始邮件 ------------------
发件人: houseme ***@***.***&gt;
发送时间: 2022年10月13日 08:15
收件人: polarismesh/polaris ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [polarismesh/polaris] fix: #672 优化日志 (PR #735)





 
@houseme commented on this pull request.
 
import 按组处理，官方包一组，第三方包一组，项目包一组
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

2022-10-13 03:09 UTC, hoErYu commented
> import 按组处理，官方包一组，第三方包一组，项目包一组

已做相关修改

2022-10-13 09:40 UTC, daheige approved these changes

2022-10-13 10:36 UTC, chuntaojun requested changes

2022-10-13 10:36 UTC, chuntaojun commented on common/log/options.go
> +	RotationMaxDuration int `yaml:"rotationMaxDuration"`
配置名称最好体现下单位信息, 或者使用 string，然后走 time.ParseDuration

2022-10-13 10:36 UTC, chuntaojun commented on common/log/queue.go
> +	queue.queueLock.Unlock()
这里的 Unlock() 是？

2022-10-13 10:36 UTC, chuntaojun commented on common/log/queue.go
> +type Node struct {
这里的实现建议去掉吧，已经有一个 timeWheel 的实现了：https://github.com/polarismesh/polaris/blob/main/common/timewheel/timewheel.go

建议定时任务、延迟任务都用这个处理

2022-10-13 10:36 UTC, chuntaojun commented on common/log/scope.go
> +func GetScopeByName(name string) *Scope {
GetScopeByName => GetScopeOrDefaultByName

2022-10-13 10:36 UTC, chuntaojun commented on common/log/type.go
> +	DiscoverEventLoggerName = "discoverEventLocal"
插件的 logger name应该定义在插件中，这里只保留 polaris-server 主体的几个 scope name

2022-10-13 11:27 UTC, hoErYu commented on common/log/options.go
> +	RotationMaxDuration int `yaml:"rotationMaxDuration"`
嗯嗯，我做对应的修改

2022-10-13 11:27 UTC, hoErYu commented on common/log/queue.go
> +	queue.queueLock.Unlock()
这是为了避免Add函数阻塞

2022-10-13 11:28 UTC, hoErYu commented on common/log/scope.go
> +func GetScopeByName(name string) *Scope {
OK，我做对应的修改

2022-10-13 11:29 UTC, hoErYu commented on common/log/type.go
> +	DiscoverEventLoggerName = "discoverEventLocal"
这个我先尝试下

2022-10-22 06:36 UTC, merged