fix: #744 修复timewheel做轮转任务时间不准确的问题
polarismesh/polaris pull request #745
Opened 2022-10-14 11:30 UTC by hoErYu

**Please provide issue(s) of this PR:**
Fixes #744

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-10-15 11:25 UTC, chuntaojun requested changes

2022-10-15 11:25 UTC, chuntaojun commented on common/timewheel/timewheel_test.go
> +	time.Sleep(11 * time.Second)
单元测试需要明确的判断结果是否正确，不要使用 fmt.Println 来做度量，建议使用 assert 或者相关度量来验证修改是正确的

2022-10-17 03:46 UTC, closed without merging

2022-10-17 03:46 UTC, chuntaojun commented
建议合并 main 的时候，走 rebase 进行合并

2022-10-17 03:53 UTC, hoErYu commented
> 建议合并 main 的时候，走 rebase 进行合并

-.-被发现了，刚是用的rebase但是好像玩坏了~