fix: 鉴权插件优化(#709)
polarismesh/polaris pull request #771
Opened 2022-10-26 07:25 UTC by alexwanglei

* fix issue #709

* AcquireContext移除token成员和WithToken方法

* 鉴权token获取在鉴权模块的权限检查中进行

* 去掉plugin/auth鉴权插件，迁移整合到auth/defaultauth中

2022-10-26 08:07 UTC, chuntaojun requested changes

2022-10-26 08:07 UTC, chuntaojun commented on apiserver/httpserver/server.go
> -	if !h.auth.IsWhiteList(segments[0]) && !h.auth.Allow(pid, pToken) {
白名单的逻辑建议单独一个插件处理下，IP白名单的逻辑不能丢

2022-10-26 08:07 UTC, chuntaojun commented on auth/defaultauth/auth.go
>  func (da *defaultAuth) CheckPermission(reqCtx interface{}, authRule interface{}) (bool, error) {
da *defaultAuth => c *defaultAuthChecker

2022-10-26 08:07 UTC, chuntaojun commented on auth/defaultauth/auth.go
> +type defaultAuth struct{}
这个就不要了

2022-10-26 08:07 UTC, chuntaojun commented on auth/defaultauth/auth_mgn.go
> +	auth     *defaultAuth
这个不需要了

2022-10-26 08:07 UTC, chuntaojun commented on auth/defaultauth/auth_mgn.go
> +	d.auth = &defaultAuth{}
这个不需要了

2022-10-27 02:36 UTC, chuntaojun commented on apiserver/httpserver/server.go
> +	allowlist         plugin.Allowlist
插件名称还是改为 WhiteList 吧会不会好点？

2022-10-27 02:36 UTC, chuntaojun commented on polaris-server.yaml
> +  allowlist:
默认注释掉，不然会有问题

2022-10-27 02:49 UTC, alexwanglei commented on apiserver/httpserver/server.go
> +	allowlist         plugin.Allowlist
OK

2022-10-27 09:52 UTC, chuntaojun commented on auth/defaultauth/auth_mgn_core.go
> +	ctx, ok := reqCtx.(*model.AcquireContext)
这里可以直接指定参数类型了，不需要在保留interface{} 做一次强转

2022-10-27 09:52 UTC, chuntaojun commented on auth/defaultauth/auth_mgn_core.go
> +func (d *defaultAuthChecker) doCheckPermission(reqCtx interface{}, authRule interface{}) (bool, error) {
这一块原来的单元测试迁移过来？

2022-10-27 11:43 UTC, alexwanglei commented on auth/defaultauth/auth_mgn_core.go
> +	ctx, ok := reqCtx.(*model.AcquireContext)
done

2022-10-27 11:45 UTC, alexwanglei commented on auth/defaultauth/auth_mgn_core.go
> +func (d *defaultAuthChecker) doCheckPermission(reqCtx interface{}, authRule interface{}) (bool, error) {
这块原来没有单元测试，但是auth_mgn_core_test.go里的测试用例已经覆盖这部分代码

2022-10-27 13:51 UTC, chuntaojun approved these changes

2022-10-27 13:52 UTC, chuntaojun commented on auth/defaultauth/auth_mgn_core.go
> +func (d *defaultAuthChecker) doCheckPermission(reqCtx interface{}, authRule interface{}) (bool, error) {
ok

2022-10-27 13:52 UTC, chuntaojun commented
LGTM

2022-11-01 01:54 UTC, chuntaojun commented
pls fix code conflict

2022-11-01 07:06 UTC, merged