Feature: improve code and improve golangci-lint config
polarismesh/polaris pull request #777
Opened 2022-10-30 14:09 UTC by houseme

**Please provide issue(s) of this PR:**
Fixes #776

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [X] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-10-31 01:26 UTC, chuntaojun commented
pls fix ci

2022-10-31 03:21 UTC, houseme commented
> pls fix ci

已处理

2022-10-31 06:23 UTC, chuntaojun requested changes

2022-10-31 06:23 UTC, chuntaojun commented on apiserver/xdsserverv3/dump.go
> +	if err != nil {
打印下 error 信息

2022-10-31 06:23 UTC, chuntaojun commented on apiserver/xdsserverv3/dump.go
> +	if err = json.Unmarshal(data, &o); err != nil {
同上

2022-10-31 06:23 UTC, chuntaojun commented on apiserver/xdsserverv3/server.go
> +	// 启动时，获取全量的 n 信息，用来推送空配置
？ 这里不要替换注释

2022-10-31 09:30 UTC, houseme commented on apiserver/xdsserverv3/dump.go
> +	if err != nil {
done

2022-10-31 09:30 UTC, houseme commented on apiserver/xdsserverv3/dump.go
> +	if err = json.Unmarshal(data, &o); err != nil {
done

2022-10-31 09:30 UTC, houseme commented on apiserver/xdsserverv3/server.go
> +	// 启动时，获取全量的 n 信息，用来推送空配置
已修复

2022-11-01 01:11 UTC, chuntaojun approved these changes

2022-11-01 01:11 UTC, merged