[ISSUE #822] self health check by leader instance
polarismesh/polaris pull request #832
Opened 2022-11-30 15:00 UTC by shichaoyuan

**Please provide issue(s) of this PR:**
Fixes #822 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [X] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-12-01 03:20 UTC, chuntaojun commented on bootstrap/self_checker.go
> +	storage, err := store.GetStore()
看下能否在 NewXxx 的时候主动传入 store 对象

2022-12-01 03:20 UTC, chuntaojun commented on bootstrap/self_checker.go
> +			if s.storage.IsLeader() {
是不是可以通过事件驱动？内部有一个协程定期轮训判断 isLeader，然后通过 eventhub 发布 LeaderChangeEvent 事件，
{
Leader bool
Follower bool
}

selfChecker 只需要监听 event 做不同的处理

2022-12-01 05:26 UTC, shichaoyuan commented on bootstrap/self_checker.go
> +			if s.storage.IsLeader() {
明白你的意思
store 层 pub 事件， 这里 sub，两边就不用直接引用了

2022-12-01 10:11 UTC, chuntaojun commented on bootstrap/self_checker.go
> +			if s.storage.IsLeader() {
是的，这样子其他地方要用的话，也只需要sub这个event即可

2022-12-02 15:41 UTC, shichaoyuan commented
@chuntaojun  先改了一版支持多leader，看一下

2022-12-03 10:47 UTC, chuntaojun commented
新增的逻辑覆盖率有点低，看看补一些测试用例吧

2022-12-04 15:09 UTC, shichaoyuan commented on service/healthcheck/server.go
> +	if err = server.storage.StartLeaderElection(server.cacheProvider.selfService); err != nil {
放在 maintain_api.go 中了。
又重构了一下

2022-12-05 03:17 UTC, chuntaojun commented
代码组织结构有点调整，辛苦处理下

2022-12-05 11:37 UTC, chuntaojun requested changes

2022-12-05 11:37 UTC, chuntaojun commented on service/healthcheck/check.go
> +	handler.cacheProvider.selfServiceInstances.Range(func(instanceId string, value ItemWithChecker) {
这里不太对吧？我理解应该是收到 leader 之后，那就开启一个定期任务，如果收到 follower，那就关闭自己的定期任务

2022-12-05 11:37 UTC, chuntaojun commented on store/mysql/maintain.go
> +	eventhub.Publish(eventhub.LeaderChangeEventTopic, store.LeaderChangeEvent{Key: le.electKey, Leader: le.isLeader()})
这里一定要定期发布吗？不需要吧？只有出现 leader/follower 状态转变才需要 publish event

2022-12-05 11:37 UTC, chuntaojun commented on store/boltdb/maintain.go
> +	go func() {
同理，这里也不需要定时的做 publish event

2022-12-05 13:30 UTC, shichaoyuan commented on service/healthcheck/check.go
> +	handler.cacheProvider.selfServiceInstances.Range(func(instanceId string, value ItemWithChecker) {
只处理变更事件也可以。 
我原来的设计是状态事件，主要是sub处理比较简单。

2022-12-05 13:34 UTC, shichaoyuan commented on store/mysql/maintain.go
> +	eventhub.Publish(eventhub.LeaderChangeEventTopic, store.LeaderChangeEvent{Key: le.electKey, Leader: le.isLeader()})
我这里调整成变更事件吧

2022-12-05 13:37 UTC, chuntaojun commented on service/healthcheck/check.go
> +	handler.cacheProvider.selfServiceInstances.Range(func(instanceId string, value ItemWithChecker) {
但是这样子的话，你的监听到事件的处理流程和发布事件者耦合了，必须不断发布 LeaderChangeEvent 来驱动，本来事件是只有变化才需要 pub 的，结果为了能够定时执行任务，你就要不停的 pub，无论是否出现了变化

2022-12-06 04:10 UTC, chuntaojun approved these changes

2022-12-06 16:19 UTC, merged