feat: 配置文件导入导出功能 (#524)
polarismesh/polaris pull request #858
Opened 2022-12-09 09:33 UTC by alexwanglei

* fix issue (#524)

2022-12-09 09:59 UTC, lepdou commented on config/common.go
> +	log.Info("StartTxAndSetToContext")
这个日志改成debug，或者去掉？

2022-12-09 10:03 UTC, lepdou commented
导出的zip包格式，现在是只能用导出来的包吗？

是不是可以支持，用户随意的把本地磁盘的一个目录压缩之后，上传到一个 file group 下吗？这种场景下，tag那些都可以不要。然后把目录转化成 / 的文件名？

比如用户有一个这样的目录:
config
-- a.txt
--- | common
           -- b.yml

直接就可以创建出 config/a.txt 和 config/common/b.yml 文件。

支持这种场景，是不是应用更广泛一点？比如用户直接把项目里的resource 目录下整个传上去，初始化迁移就很方便。

2022-12-09 10:03 UTC, lepdou commented
另外，导入的时候，文件冲突是怎么解决的？直接覆盖还是？可能要考虑一下

2022-12-09 10:16 UTC, chuntaojun commented
> 导出的zip包格式，现在是只能用导出来的包吗？
> 
> 是不是可以支持，用户随意的把本地磁盘的一个目录压缩之后，上传到一个 file group 下吗？这种场景下，tag那些都可以不要。然后把目录转化成 / 的文件名？
> 
> 比如用户有一个这样的目录: config -- a.txt --- | common -- b.yml
> 
> 直接就可以创建出 config/a.txt 和 config/common/b.yml 文件。
> 
> 支持这种场景，是不是应用更广泛一点？比如用户直接把项目里的resource 目录下整个传上去，初始化迁移就很方便。

感觉有很多种？

1. 直接导入，比如期望同时导入到多个 ns 当中去
2. 期望导入的时候，可以根据一些方式直接导入到我期望的多个group
3. 单个 group 下的导入导出

2022-12-09 10:19 UTC, chuntaojun commented
为了避免贡献者太多的代码改的，可以先在相关 issue 再次讨论下，确定下最终导入导出的方案

2022-12-09 10:20 UTC, chuntaojun commented
> 另外，导入的时候，文件冲突是怎么解决的？直接覆盖还是？可能要考虑一下

这个确实需要考虑，是不是走页面提示比较好？或者导入的时候用户可以选择导入规则

1. 冲突不覆盖
2. 冲突覆盖

2022-12-09 13:26 UTC, alexwanglei commented
> > 另外，导入的时候，文件冲突是怎么解决的？直接覆盖还是？可能要考虑一下
> 
> 这个确实需要考虑，是不是走页面提示比较好？或者导入的时候用户可以选择导入规则
> 
> 1. 冲突不覆盖
> 2. 冲突覆盖
> 
> 无论选择哪一种，都需要给出冲突的列表以及冲突的最终处理结果？

在同命名空间的同组下导入同名的配置文件，在创建配置文件时会报资源已存在的错误。这块时复用的创建配置文件的逻辑。

2022-12-09 13:32 UTC, alexwanglei commented
> 导出的zip包格式，现在是只能用导出来的包吗？
> 
> 是不是可以支持，用户随意的把本地磁盘的一个目录压缩之后，上传到一个 file group 下吗？这种场景下，tag那些都可以不要。然后把目录转化成 / 的文件名？
> 
> 比如用户有一个这样的目录: config -- a.txt --- | common -- b.yml
> 
> 直接就可以创建出 config/a.txt 和 config/common/b.yml 文件。
> 
> 支持这种场景，是不是应用更广泛一点？比如用户直接把项目里的resource 目录下整个传上去，初始化迁移就很方便。

现在就是按照zip包中的目录结构导入的，namespace/group/file，META文件主要为了记录配置文件的Tags信息，没有META文件也可以导入。
<img width="688" alt="image" src="https://user-images.githubusercontent.com/5691346/206713624-48b355b5-7fd8-44a7-8dbf-6669b9494ac4.png">

2022-12-09 13:39 UTC, alexwanglei commented
> > 导出的zip包格式，现在是只能用导出来的包吗？
> > 是不是可以支持，用户随意的把本地磁盘的一个目录压缩之后，上传到一个 file group 下吗？这种场景下，tag那些都可以不要。然后把目录转化成 / 的文件名？
> > 比如用户有一个这样的目录: config -- a.txt --- | common -- b.yml
> > 直接就可以创建出 config/a.txt 和 config/common/b.yml 文件。
> > 支持这种场景，是不是应用更广泛一点？比如用户直接把项目里的resource 目录下整个传上去，初始化迁移就很方便。
> 
> 感觉有很多种？
> 
> 1. 直接导入，比如期望同时导入到多个 ns 当中去
> 2. 期望导入的时候，可以根据一些方式直接导入到我期望的多个group
> 3. 单个 group 下的导入导出

若要支持各种灵活的导入场景，导入接口可能需要增加比较复杂的参数。目前只有一个zip文件参数，等于约定了按照zip文件目录结构去映射命名空间-组-配置文件的方式去导入。

2022-12-09 14:00 UTC, alexwanglei commented on config/common.go
> +	log.Info("StartTxAndSetToContext")
done

2022-12-12 02:16 UTC, lepdou commented
要不先搞简单一点，先支持跨namespace的导出导入

2022-12-12 02:25 UTC, chuntaojun commented
> 要不先搞简单一点，先支持跨namespace的导出导入

导入的格式呢？是这种让用户按照规则组织一下，还是怎么处理？

2022-12-15 11:13 UTC, lepdou commented
> > 要不先搞简单一点，先支持跨namespace的导出导入
> 
> 导入的格式呢？是这种让用户按照规则组织一下，还是怎么处理？

现在应该只能信先导出，再导入。用户不需要自己处理规则把？

2023-01-30 08:07 UTC, andrewshan commented
hi,alex. We have move all the proto into https://github.com/polarismesh/specification, pls make your change into this repo

2023-02-08 03:04 UTC, alexwanglei commented on config/config_file.go
> +			_, files, err := s.storage.QueryConfigFilesByGroup(namespace, group, 0, 100)
导出全部配置是指导出命名空间下的全部配置吗？目前实现只有两类导出：

2023-02-08 03:07 UTC, chuntaojun commented on config/config_file.go
> +			_, files, err := s.storage.QueryConfigFilesByGroup(namespace, group, 0, 100)
这个接口是分页查询，你只查询一次，不一定可以查询出某个配置分组下的全部配置

2023-02-08 03:12 UTC, alexwanglei commented on config/config_file.go
> +			_, files, err := s.storage.QueryConfigFilesByGroup(namespace, group, 0, 100)
对，这里默认每个分组只查了100个

2023-02-08 08:31 UTC, chuntaojun requested changes

2023-02-08 08:31 UTC, chuntaojun commented on config/config_file.go
> +// ExportConfigFile 导出配置文件
配置的导入导出专门一个 code file ？

2023-02-08 09:22 UTC, alexwanglei commented on config/config_file.go
> +			_, files, err := s.storage.QueryConfigFilesByGroup(namespace, group, 0, 100)
调整成循环拉取全部配置了

2023-02-08 09:30 UTC, alexwanglei commented on config/config_file.go
> +// ExportConfigFile 导出配置文件
是因为config_file.go太长了吗？逻辑上还是属于config_file的操作，放在一起感觉问题不大。

2023-02-08 09:58 UTC, chuntaojun approved these changes

2023-02-08 09:58 UTC, chuntaojun commented
等 1.14.0 分支打出来之后，在进行合并改 PR

2023-02-15 07:40 UTC, merged